config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/list'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]

    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create
        @todo = Todo.new(todo_params)
        @todo.save
        redirect_to todos_path
    end

    def show
    end

    def edit
    end

    def destroy
        @todo.destroy
        redirect_to todos_path
    end

    def update
        @todo.update(todo_params)
        redirect_to todos_path
    end

    def complete
        @todo.update(completed: true)
        redirect_to todos_path
    end

    def list
        @todos = Todo.all
    end

    private
    def todo_params
        params.require(:todo).permit(:description, :completed)
    end

    def find_todo
        @todo = Todo.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= render 'todos/navbar'%>
  <body class="container pt-3">
    <div class="pb-5"></div>
    <%= yield %>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f|%>
    <%= f.label :description, "Descripción"%>
    <%= f.text_field :description %>

    <%= f.label :completed, "Completado"%>
    <%= f.check_box :completed %>

    <%= f.submit 'Modificar'%>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="<%= todos_path %>">Index</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= todos_list_path %>">List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= todos_new_path %>">Nuevo Formulario</a>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<%= render 'todos/form'%>

app/views/todos/index.html.erb
<h1>Listado de To do</h1>
<hr>
<% @todos.each do |todo|%>
    
    <div class="card card-body bg-light">To do Nº: <%= todo.id %></div>
    <div class="card card-body bg-light">Descripción: <%= todo.description %></div>
    <div class="card card-body bg-light">Completado: <%= todo.completed %></div>
    <div class="card card-body bg-light"> <%= link_to "Completar", complete_path(todo), class:"btn btn-primary"%> </div>

    <div class="card card-body bg-light"> <%= link_to "Más detalle", todo %> </div>
    <div class="card card-body bg-light"> <%= link_to "Editar", edit_path(todo)  %> </div>
    <div class="card card-body bg-light"> <%= link_to "Borrar", todo, method: :delete %> </div>
    <p></p>
<% end %>

<div> <%= link_to "Crear To do", todos_new_path, class:"btn btn-primary mb-6"%> </div>
<p></p>

app/views/todos/list.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm">
     <h2>No Completados</h2>
        <% @todos.each do |todo|%>
            <% if todo.completed == false %>
                <li><%= todo.description %></li>
            <% end %>
        <% end %>
    </div>

    <div class="col-sm">
    <h2>Completados</h2>
       <% @todos.each do |todo|%>
            <% if todo.completed == true %>
                <li><%= todo.description %></li>
            <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<%= render 'todos/form'%>

app/views/todos/show.html.erb
<h1> Descripción: <%= @todo.description  %></h1>
<h2> Completado: <%= @todo.completed %></h2>
<div> <%= link_to "Volver", todos_path%> </div>